server:
  port: 8989
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Frank8040/Backend-2023-1.git
          search-paths: config-data
          username: Frank8040
          password: frankchunca.77298040
          default-label: main
  security:
    user:
      name: root
      password: s3cr3t
